### ISSUE TITLE
provide runtime repository for evaluation models

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-decision#34]
The DmnDiagramEvaluationModel has to be extracted from the xml-content directly, since the data stored in camundas internal act_ tables is not sufficient.
This might be an expensive task, since the xml can get big and has to be read and parsed into a DmnDiagram.  As the diagram itself does not chenage over time (new revisons might be deployed), this model can be cached.

Idea mvp:

* On engine  start, find all already deployed diagrams, read the xml and store the evaluationModel in a repository
* on deployment of a new diagram (hint: DmnTrasformListener), add the new evaluationModel to the repository

"repository" in this case means "an interface that allows to save and load (optionally find) evaluation models for execution. It can be a simple in memory hashmap/cache. Later we can add implementations that store in sql tables or use the act_ge_bytearray table.

AC:

* start up engine with two deployed diagrams -> find both in the repository
* deploy a new diagram -> find the new one in the repo as well.

**Comment by zambrovski** [comment]
Just for inspiration, have a look on https://github.com/holunda-io/camunda-bpm-taskpool/tree/develop/engine/taskpool-collector/src/main/kotlin/io/holunda/camunda/taskpool/process
